name: wordy
version: 0.1.0.0

dependencies:
  - base

library:
  exposed-modules: WordProblem
  source-dirs: src
  ghc-options: -Wall
  dependencies: parsec

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - wordy
      - hspec
